name: Build
run-name: Build
on: [push]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Install SDL2
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      
      - name: Create build directory
        run: mkdir build

      - name: Configure project with CMake
        run: cmake -S . -B build

      - name: "Test"
        run: ls -la

      - uses: actions/checkout@v4
      - name: Add permission for building
        run: chmod +x ./Engine/build.sh   
      - name: Run build engine script
        run: ./Engine/build.sh