name: Build
run-name: Build
on: [push]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: Add permission for building
        run: chmod +x ./Engine/build.sh   
      - name: Run build engine script
        run: ./Engine/build.sh