name: Build
run-name: Build
on: [push]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
          
      - name: 'Configure and build your project'
        run: |
          cmake -S . -B build
          cmake --build build --verbose

      - name: "Test"
        run: ls -la

      - uses: actions/checkout@v4
      - name: Add permission for building
        run: chmod +x ./Engine/build.sh   
      - name: Run build engine script
        run: ./Engine/build.sh